
#Application Configuration
server:
  port: 8092

spring:
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:mysql://localhost/portfolio_mysql?allowPublicKeyRetrieval=true&useSSL=false&serverTimeZone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    platform: MySQL
    username: root
    password: Chito11.

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
